version: '3'
services:
  hello:
    container_name: hello
    image: springboot-helloworld:latest
    restart: on-failure:1
    ports:
      - 8080:8080
    env_file:
      - .env
    network_mode: bridge